#!/usr/bin/env bash
# Write skills/.../repo/workspace.env for multi-repo AI-Summarizer use.
# Does NOT merge DBs. Each sibling must have its own skill install.
#
# Usage:
#   ./configure_workspace.sh /path/to/target_repo \
#     --id know_to_win --role app \
#     --sibling api=/path/to/ktw_do_react_api \
#     --prefix know_to_win=package:know_to_win/
#
set -euo pipefail

usage() {
  cat >&2 <<'EOF'
usage:
  configure_workspace.sh <target_repo> [options]

options:
  --id ID                 WORKSPACE_REPO_ID
  --role ROLE             app|api|lib|other
  --sibling id=/abs/path  repeatable; WORKSPACE_SIBLINGS
  --prefix key=package:…  repeatable; WORKSPACE_PACKAGE_PREFIXES
  --cross 0|1             WORKSPACE_CROSS_CONTRACTS (default 0)
  --install               run install.sh first if skill missing

Each sibling needs:
  <sibling>/skills/agent_token_usage_optimization/{summaries,repo/index.sqlite,repo/adjacency.sqlite}
EOF
  exit 1
}

[[ $# -lt 1 ]] && usage
TARGET=""
ID=""
ROLE="app"
CROSS="0"
DO_INSTALL=0
SIBLINGS=()
PREFIXES=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --id) ID="${2:-}"; shift 2 ;;
    --role) ROLE="${2:-}"; shift 2 ;;
    --sibling) SIBLINGS+=("${2:-}"); shift 2 ;;
    --prefix) PREFIXES+=("${2:-}"); shift 2 ;;
    --cross) CROSS="${2:-0}"; shift 2 ;;
    --install) DO_INSTALL=1; shift ;;
    -h|--help) usage ;;
    *)
      if [[ -z "$TARGET" ]]; then TARGET="$1"; shift
      else echo "unknown arg: $1" >&2; usage
      fi
      ;;
  esac
done

[[ -z "$TARGET" || ! -d "$TARGET" ]] && { echo "error: target repo required" >&2; exit 1; }
TARGET="$(cd "$TARGET" && pwd)"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILL="$TARGET/skills/agent_token_usage_optimization"

if [[ ! -d "$SKILL" ]]; then
  if [[ $DO_INSTALL -eq 1 ]]; then
    "$SCRIPT_DIR/install.sh" "$TARGET"
  else
    echo "error: skill not installed at $SKILL" >&2
    echo "       run: $SCRIPT_DIR/install.sh $TARGET   or pass --install" >&2
    exit 1
  fi
fi

[[ -z "$ID" ]] && ID="$(basename "$TARGET")"

SIB_JOIN=""
for s in "${SIBLINGS[@]+"${SIBLINGS[@]}"}"; do
  [[ -z "$s" ]] && continue
  if [[ "$s" != *=* ]]; then
    echo "error: --sibling must be id=/path (got $s)" >&2
    exit 1
  fi
  sid="${s%%=*}"
  spath="${s#*=}"
  spath="${spath/#\~/$HOME}"
  if [[ -d "$spath" ]]; then
    spath="$(cd "$spath" && pwd)"
  else
    echo "warning: sibling path not a directory yet: $spath" >&2
  fi
  if [[ -n "$SIB_JOIN" ]]; then SIB_JOIN+=","; fi
  SIB_JOIN+="${sid}=${spath}"
  if [[ ! -d "$spath/skills/agent_token_usage_optimization" ]]; then
    echo "warning: $sid has no skill install — run install.sh there and index/summarize separately" >&2
  fi
done

PREF_JOIN=""
for p in "${PREFIXES[@]+"${PREFIXES[@]}"}"; do
  [[ -z "$p" ]] && continue
  if [[ -n "$PREF_JOIN" ]]; then PREF_JOIN+=","; fi
  PREF_JOIN+="$p"
done

OUT="$SKILL/repo/workspace.env"
mkdir -p "$SKILL/repo"
cat >"$OUT" <<EOF
# Generated by configure_workspace.sh — local machine paths; do not commit
WORKSPACE_REPO_ID=$ID
WORKSPACE_ROLE=$ROLE
WORKSPACE_SIBLINGS=$SIB_JOIN
WORKSPACE_PACKAGE_PREFIXES=$PREF_JOIN
WORKSPACE_CROSS_CONTRACTS=$CROSS
EOF

echo "wrote $OUT"
echo "---"
cat "$OUT"
echo "---"
echo "next:"
echo "  cd $TARGET"
echo "  python3 skills/agent_token_usage_optimization/broker.py index"
echo "  python3 skills/agent_token_usage_optimization/summary_broker.py workspace"
echo "  # sibling repos: install skill + index + summarize THERE (separate DBs)"
